from pathlib import Path
root=Path('/mnt/data/kannada_work')
kn=root/'kn'; kn.mkdir(exist_ok=True)
common_css='../css/style.css'
lang_js='../js/language.js'
img='../images/'
places='../images/places/'

nav=[('ಮುಖಪುಟ','index.html'),('ವಾಸ್ತವ್ಯ','rooms.html'),('ನಮ್ಮ ಬಗ್ಗೆ','about.html'),('ಚಿತ್ರಗಳು','gallery.html'),('ಸುತ್ತಮುತ್ತ','things-to-do.html'),('ಸ್ಥಳ','location.html'),('ಸಂಪರ್ಕ','contact.html')]

def header(active):
    items=''.join(f'<li><a href="{u}"'+(' aria-current="page"' if u==active else '')+f'>{t}</a></li>' for t,u in nav)
    mobile=''.join(f'<li><a href="{u}">{t}</a></li>' for t,u in nav)
    return f'''<header class="site-header"><div class="container header-inner">
<a href="index.html" class="brand"><svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><rect width="64" height="64" rx="8" fill="#1c2b1a"/><path d="M14 40C22 26 30 20 50 16" stroke="#efe6d0" stroke-width="2.5" stroke-linecap="round"/><path d="M12 48C22 36 34 30 52 26" stroke="#a8532e" stroke-width="2.5" stroke-linecap="round"/></svg><span>The Coorg Chimm's<span class="brand-sub">Camptime Homestay</span></span></a>
<nav class="main-nav" aria-label="ಮುಖ್ಯ ನ್ಯಾವಿಗೇಶನ್"><ul>{items}</ul></nav>
<div class="header-ctas"><a href="#" data-cta="call" class="btn btn-ghost btn-sm">ಕರೆ ಮಾಡಿ</a><a href="contact.html" class="btn btn-primary btn-sm">ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a></div>
<button class="nav-toggle" aria-label="ಮೆನು ತೆರೆಯಿರಿ" aria-expanded="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button></div></header>
<div class="mobile-menu" role="dialog" aria-modal="true" aria-label="ಮುಖ್ಯ ಮೆನು"><div class="mobile-menu-top"><span class="brand" style="color:#fff;">The Coorg Chimm's</span><button class="mobile-menu-close" aria-label="ಮುಚ್ಚಿರಿ"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><line x1="5" y1="5" x2="19" y2="19"/><line x1="19" y1="5" x2="5" y2="19"/></svg></button></div><ul>{mobile}</ul><div class="mobile-cta-row"><a href="#" data-cta="whatsapp" class="btn btn-whatsapp">ವಾಟ್ಸ್ಆಪ್‌ನಲ್ಲಿ ಮಾತಾಡಿ</a><a href="#" data-cta="call" class="btn btn-outline">ಕರೆ <span data-phone-display></span></a></div></div>'''

def footer():
    return '''<footer class="site-footer"><div class="container footer-grid"><div><div class="footer-brand">The Coorg Chimm's Camptime Homestay</div><p>ಕೊಡಗಿನ ಹಸಿರಿನ ನಡುವೆ, ಕುಟುಂಬ ಮತ್ತು ಸ್ನೇಹಿತರಿಗಾಗಿ ಸಂಪೂರ್ಣ ಖಾಸಗಿ ವಾಸ್ತವ್ಯ.</p></div><div><h4>ಅನ್ವೇಷಿಸಿ</h4><ul><li><a href="rooms.html">ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ</a></li><li><a href="things-to-do.html">ಸುತ್ತಮುತ್ತಲಿನ ತಾಣಗಳು</a></li><li><a href="gallery.html">ಚಿತ್ರಗಳ ಗ್ಯಾಲರಿ</a></li></ul></div><div><h4>ಪ್ರವಾಸ</h4><ul><li><a href="travel-guide.html">ಕೊಡಗು ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ</a></li><li><a href="best-time-to-visit.html">ಭೇಟಿಗೆ ಸೂಕ್ತ ಕಾಲ</a></li><li><a href="how-to-reach.html">ಹೇಗೆ ತಲುಪುವುದು?</a></li></ul></div><div><h4>ಸಂಪರ್ಕ</h4><ul><li><a href="#" data-cta="call">+91 99726 26256</a></li><li><a href="#" data-cta="whatsapp">ವಾಟ್ಸ್ಆಪ್</a></li><li><a href="location.html">ಸ್ಥಳ ಮತ್ತು ದಾರಿ</a></li></ul></div></div><div class="container footer-bottom"><span>© 2026 The Coorg Chimm's Camptime Homestay</span><span><a href="privacy-policy.html">ಗೌಪ್ಯತಾ ನೀತಿ</a> · <a href="terms.html">ನಿಯಮಗಳು</a></span></div></footer><div class="mobile-bottom-cta"><a href="#" data-cta="call">☎ <span>ಕರೆ</span></a><a href="#" data-cta="whatsapp">● <span>ವಾಟ್ಸ್ಆಪ್</span></a></div>'''

def shell(title,desc,active,body):
    return f'''<!doctype html><html lang="kn"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{title}</title><meta name="description" content="{desc}"><meta name="robots" content="index, follow"><link rel="canonical" href="https://www.coorgchimmscamptime.com/kn/{active}"><link rel="icon" type="image/svg+xml" href="../images/favicon.svg"><link rel="stylesheet" href="{common_css}"><script src="{lang_js}" defer></script><meta property="og:locale" content="kn_IN"><meta property="og:type" content="website"><meta property="og:site_name" content="The Coorg Chimm's Camptime Homestay"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:url" content="https://www.coorgchimmscamptime.com/kn/{active}"></head><body><a class="skip-link" href="#main">ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ತೆರಳಿ</a>{header(active)}<main id="main">{body}</main>{footer()}<script src="../js/main.js" defer></script></body></html>'''

def img(src,alt,cls='ratio-16-9'):
    return f'<div class="img-ph {cls}"><img src="{imgroot(src)}" alt="{alt}" loading="lazy" decoding="async"></div>'
def imgroot(src): return '../images/'+src

# Home
body=f'''
<section class="hero"><div class="hero-media"><div class="img-ph" style="position:absolute;inset:0;border:none;border-radius:0;aspect-ratio:auto;"><img src="../images/coorg-homestay-hero.webp" alt="ಕೊಡಗಿನ ಹಸಿರಿನ ನಡುವೆ ಇರುವ ದಿ ಕೂರ್ಗ್ ಚಿಮ್ಮ್ಸ್ ಕ್ಯಾಂಪ್‌ಟೈಮ್ ಹೋಂಸ್ಟೇ" width="1536" height="864" fetchpriority="high" decoding="async"></div></div><div class="hero-mist"></div><div class="hero-content container"><p class="eyebrow" style="color:#efe6d0;">ಸೂಂಟಿಕೊಪ್ಪ · ಕೊಡಗು, ಕರ್ನಾಟಕ</p><h1>ಕೊಡಗಿನ ಹಸಿರ ನಡುವೆ… ಒಂದು ನೆಮ್ಮದಿಯ ತಂಗುದಾಣ.</h1><p class="hero-lede">ಉಲುಗುಳಿ ಗ್ರಾಮದ ಕಾಫಿ ತೋಟಗಳ ಸೊಗಡಿನ ನಡುವೆ, ಬೆಳಗಿನ ಮಂಜು, ಹಕ್ಕಿಗಳ ಕಲರವ ಮತ್ತು ಮಲೆನಾಡಿನ ಮೌನದೊಂದಿಗೆ ನಿಧಾನವಾಗಿ ದಿನ ಆರಂಭಿಸುವ ನಿಮ್ಮದೇ ಖಾಸಗಿ ವಾಸ್ತವ್ಯ.</p><div class="hero-ctas"><a href="contact.html" class="btn btn-primary">ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a><a href="rooms.html" class="btn btn-outline">ಹೋಂಸ್ಟೇ ನೋಡಿ</a><a href="#" data-cta="whatsapp" class="btn btn-outline">ವಾಟ್ಸ್ಆಪ್‌ನಲ್ಲಿ ಮಾತಾಡಿ</a></div></div><svg class="hero-contour" viewBox="0 0 1440 60" preserveAspectRatio="none" aria-hidden="true"><path d="M0 40C240 10 400 55 720 30C1040 5 1200 45 1440 20V60H0V40Z" fill="currentColor"/></svg></section>
<section><div class="container"><p class="eyebrow">ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ</p><h2 class="max-w-prose">ಕುಟುಂಬ ಮತ್ತು ಸ್ನೇಹಿತರಿಗಾಗಿ — ಒಂದೇ ಸೂರಿನಡಿ ನಿಮ್ಮದೇ ಖಾಸಗಿ ವಾಸ್ತವ್ಯ.</h2><div class="grid grid-4" style="margin-top:2rem;"><div class="feature"><h3>ಸಂಪೂರ್ಣ ಆಸ್ತಿ</h3><p>ಹೋಂಸ್ಟೇಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಒಂದೇ ಘಟಕವಾಗಿ ನೀಡಲಾಗುತ್ತದೆ; ಕೊಠಡಿಗಳನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ಕಾಯ್ದಿರಿಸುವ ವ್ಯವಸ್ಥೆಯಿಲ್ಲ.</p></div><div class="feature"><h3>3 ಮಲಗುವ ಕೋಣೆಗಳು</h3><p>ಮೂರು ಕೋಣೆಗಳೂ ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ವಾಸ್ತವ್ಯದ ಭಾಗವಾಗಿವೆ.</p></div><div class="feature"><h3>2 ಸ್ನಾನಗೃಹಗಳು</h3><p>ಅತಿಥಿಗಳಿಗಾಗಿ ಎರಡು ಸ್ನಾನಗೃಹಗಳಿವೆ.</p></div><div class="feature"><h3>4–12 ಅತಿಥಿಗಳು</h3><p>ಕುಟುಂಬಗಳು ಮತ್ತು ಸ್ನೇಹಿತರ ಗುಂಪುಗಳಿಗೆ ಸೂಕ್ತ; ಕನಿಷ್ಠ 4, ಗರಿಷ್ಠ 12 ಅತಿಥಿಗಳು.</p></div></div></div></section>
<section class="section-beige"><div class="container"><div class="split"><div class="split-copy"><p class="eyebrow">ಕೊಡಗಿನ ಅನುಭವ</p><h2>ಕಾಫಿಯ ಪರಿಮಳ, ಮಳೆಯ ಮಂಜು, ಮಲೆನಾಡಿನ ಮೌನ.</h2><p>ಕೊಡಗು ಎಂದರೆ ಕಾಫಿ ತೋಟಗಳ ಅಲೆಗಳಂತೆ ಹರಡುವ ಹಸಿರು, ಬೆಟ್ಟಗಳ ತಂಪು ಗಾಳಿ ಮತ್ತು ಮಣ್ಣಿನ ಸೊಗಡು. ಉಲುಗುಳಿ ಗ್ರಾಮದ ಈ ನೆಮ್ಮದಿಯ ತಾಣದಿಂದ ದಿನವನ್ನು ನಿಮ್ಮದೇ ವೇಗದಲ್ಲಿ ಆರಂಭಿಸಿ.</p><p>ಬೆಳಗಿನ ಕಾಫಿಯ ಸವಿಯ ನಂತರ ಜಲಪಾತ, ಬೆಟ್ಟ, ಕೋಟೆ, ದೇವಾಲಯ ಅಥವಾ ಕಾಫಿ ತೋಟದತ್ತ ಹೊರಡಿ; ಸಂಜೆ ಮರಳಿ ಬಂದಾಗ ಮತ್ತೆ ಅದೇ ಮೌನ ನಿಮ್ಮನ್ನು ಕಾಯುತ್ತದೆ.</p></div><div class="split-media">{img('coorg-homestay-entrance-greenery.webp','ಉಲುಗುಳಿಯ ಹಸಿರಿನ ನಡುವೆ ಇರುವ ಹೋಂಸ್ಟೇಯ ಪ್ರವೇಶದ್ವಾರ','tall')}</div></div></div></section>
<section><div class="container"><p class="eyebrow">ಕೊಡಗನ್ನು ಅರಿಯೋಣ</p><h2>ಪ್ರಯಾಣದ ಪ್ರತಿಯೊಂದು ಹೆಜ್ಜೆಯಲ್ಲೂ ಒಂದು ಕಥೆ.</h2><p class="max-w-prose">ಕಾಫಿ ತೋಟಗಳಿಂದ ಜಲಪಾತಗಳವರೆಗೆ, ಮಂಜು ಮುಸುಕಿದ ಬೆಟ್ಟಗಳಿಂದ ಕೊಡಗಿನ ಸಂಸ್ಕೃತಿಯವರೆಗೆ — ನಿಮಗೆ ಇಷ್ಟವಾದ ಅನುಭವವನ್ನು ಆರಿಸಿಕೊಳ್ಳಿ.</p><div class="grid grid-3" style="margin-top:2rem;">{''.join([f'<a class="card" href="things-to-do.html"><div class="img-ph ratio-16-9"><img src="{p}" alt="{a}" loading="lazy"></div><div class="card-body"><span class="tag">{tag}</span><h3>{h}</h3><p>{d}</p><span class="btn btn-ghost btn-sm">ಇನ್ನಷ್ಟು ನೋಡಿ</span></div></a>' for p,a,tag,h,d in [('../images/places/coffee-plantations.svg','ಕೊಡಗಿನ ಕಾಫಿ ತೋಟಗಳು','ತೋಟಗಳು','ಕಾಫಿ ಮತ್ತು ತೋಟಗಳ ಸೊಗಡು','ಕಾಫಿಯ ಪರಿಮಳದ ನಡುವೆ ನಿಧಾನವಾಗಿ ಹೆಜ್ಜೆ ಹಾಕಿ.'),('../images/places/waterfalls-nature.svg','ಕೊಡಗಿನ ಜಲಪಾತ ಮತ್ತು ಪ್ರಕೃತಿ','ಪ್ರಕೃತಿ','ಜಲಪಾತ ಮತ್ತು ಹಸಿರು','ಮಳೆಯ ಹನಿಗಳಿಂದ ಜೀವ ತುಂಬಿದ ಜಲಪಾತಗಳತ್ತ ಹೊರಡಿ.'),('../images/places/hills-viewpoints.svg','ಕೊಡಗಿನ ಬೆಟ್ಟ ಮತ್ತು ನೋಟಗಳು','ಬೆಟ್ಟಗಳು','ಬೆಟ್ಟಗಳ ಬೆರಗು','ಮಂಜಿನ ನಡುವೆ ದೂರದ ಕಣಿವೆಗಳನ್ನು ಕಣ್ತುಂಬಿಕೊಳ್ಳಿ.'),('../images/places/wildlife-adventure.svg','ಕೊಡಗಿನ ಕಾಡು ಮತ್ತು ಸಾಹಸ','ಸಾಹಸ','ಕಾಡು ಮತ್ತು ಸಾಹಸ','ನದಿ, ಕಾಡು ಮತ್ತು ಹೊರಾಂಗಣ ಅನುಭವಗಳಿಗೆ ಒಂದು ದಿನ ಮೀಸಲಿಡಿ.'),('../images/places/culture-heritage.svg','ಕೊಡಗಿನ ಸಂಸ್ಕೃತಿ ಮತ್ತು ಪರಂಪರೆ','ಪರಂಪರೆ','ಸಂಸ್ಕೃತಿ ಮತ್ತು ಪರಂಪರೆ','ಸ್ಥಳೀಯ ಇತಿಹಾಸ, ವಾಸ್ತುಶಿಲ್ಪ ಮತ್ತು ವೈವಿಧ್ಯತೆಯನ್ನು ಅರಿಯಿರಿ.'),('../images/places/local-food-experiences.svg','ಕೊಡಗಿನ ಸ್ಥಳೀಯ ರುಚಿ','ರುಚಿ','ಸ್ಥಳೀಯ ಆಹಾರ ಮತ್ತು ಅನುಭವಗಳು','ಕೊಡಗಿನ ಮಣ್ಣಿನ ಸೊಗಡಿನೊಂದಿಗೆ ಬೆಸೆದ ಸ್ಥಳೀಯ ರುಚಿಗಳನ್ನು ಸವಿಯಿರಿ.')]])}</div></div></section>
<section class="section-beige"><div class="container"><p class="eyebrow">ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ</p><h2>ಪ್ರಯಾಣವನ್ನು ಮುಂಚಿತವಾಗಿಯೇ ಸುಂದರವಾಗಿಸಿಕೊಳ್ಳಿ.</h2><div class="grid grid-3"><a class="card" href="travel-guide.html"><div class="card-body"><h3>ಕೊಡಗು ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ</h3><p>ಪ್ರದೇಶ, ಹವಾಮಾನ ಮತ್ತು ಪ್ರವಾಸದ ಉಪಯುಕ್ತ ಮಾಹಿತಿ.</p></div></a><a class="card" href="best-time-to-visit.html"><div class="card-body"><h3>ಭೇಟಿಗೆ ಸೂಕ್ತ ಕಾಲ</h3><p>ನಿಮಗೆ ಬೇಕಾದ ಕೊಡಗಿನ ಅನುಭವಕ್ಕೆ ತಕ್ಕ ಋತುವನ್ನು ಆರಿಸಿ.</p></div></a><a class="card" href="how-to-reach.html"><div class="card-body"><h3>ಹೇಗೆ ತಲುಪುವುದು?</h3><p>ವಿಮಾನ, ರೈಲು ಮತ್ತು ರಸ್ತೆಯ ಮೂಲಕ ತಲುಪುವ ಮಾರ್ಗಗಳು.</p></div></a></div></div></section>
<section class="text-center"><div class="container"><h2>ಕೊಡಗಿನ ನೆಮ್ಮದಿಗೆ ಒಂದು ಹೆಜ್ಜೆ ಇಡಿ.</h2><p class="max-w-prose mx-auto">ದಿನಾಂಕ ಮತ್ತು ಅತಿಥಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ಕಳುಹಿಸಿ. ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ಕುರಿತು ವಿಚಾರಿಸಿ.</p><div class="hero-ctas" style="justify-content:center;"><a href="contact.html" class="btn btn-primary">ನಿಮ್ಮ ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a><a href="location.html" class="btn btn-ghost">ಸ್ಥಳ ನೋಡಿ</a></div></div></section>'''
kn.joinpath('index.html').write_text(shell('ಕೊಡಗಿನ ಖಾಸಗಿ ಹೋಂಸ್ಟೇ | The Coorg Chimm’s Camptime Homestay','ಸೂಂಟಿಕೊಪ್ಪ ಸಮೀಪದ ಕೊಡಗಿನ ಉಲುಗುಳಿಯಲ್ಲಿ 4ರಿಂದ 12 ಅತಿಥಿಗಳಿಗೆ ಸಂಪೂರ್ಣ ಖಾಸಗಿ 3 ಮಲಗುವ ಕೋಣೆಗಳ ಹೋಂಸ್ಟೇ.', 'index.html', body),encoding='utf-8')

pages={
'rooms.html':('ಸಂಪೂರ್ಣ 3 ಕೋಣೆಗಳ ಹೋಂಸ್ಟೇ | ಕೊಡಗು','ಕುಟುಂಬ ಮತ್ತು ಸ್ನೇಹಿತರಿಗಾಗಿ 3 ಮಲಗುವ ಕೋಣೆಗಳು, 2 ಸ್ನಾನಗೃಹಗಳು ಮತ್ತು 1 ಅಡುಗೆಮನೆಯೊಂದಿಗೆ ಸಂಪೂರ್ಣ ಖಾಸಗಿ ಹೋಂಸ್ಟೇ.', '''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ</p><h1>ಮೂರು ಕೋಣೆಗಳು. ಒಂದೇ ಖಾಸಗಿ ವಾಸ್ತವ್ಯ.</h1><p>ಉಲುಗುಳಿಯ ಹಸಿರಿನ ನಡುವೆ 4ರಿಂದ 12 ಅತಿಥಿಗಳಿಗಾಗಿ ಸಂಪೂರ್ಣ ಆಸ್ತಿಯನ್ನು ಒಂದೇ ಘಟಕವಾಗಿ ಅನುಭವಿಸಿ.</p></div></section><section><div class="container"><div class="split"><div>{IMG('coorg-homestay-property.webp','ಕೊಡಗಿನ ಹೋಂಸ್ಟೇಯ ಹೊರಾಂಗಣ','tall')}</div><div class="split-copy"><p class="eyebrow">ಖಾಸಗಿ ಆಸ್ತಿ</p><h2>ಒಂದೇ ಸೂರಿನಡಿ ಎಲ್ಲರೂ ಜೊತೆಯಾಗಿ.</h2><p>ಈ ಹೋಂಸ್ಟೇಯ ಮೂರು ಮಲಗುವ ಕೋಣೆಗಳು, ಎರಡು ಸ್ನಾನಗೃಹಗಳು ಮತ್ತು ಅಡುಗೆಮನೆ ಸೇರಿ ಸಂಪೂರ್ಣ ಆಸ್ತಿಯನ್ನು ಒಂದೇ ವಾಸ್ತವ್ಯವಾಗಿ ನೀಡಲಾಗುತ್ತದೆ.</p><div class="grid grid-4"><div class="feature"><h3>3</h3><p>ಮಲಗುವ ಕೋಣೆಗಳು</p></div><div class="feature"><h3>2</h3><p>ಸ್ನಾನಗೃಹಗಳು</p></div><div class="feature"><h3>1</h3><p>ಅಡುಗೆಮನೆ</p></div><div class="feature"><h3>4–12</h3><p>ಅತಿಥಿಗಳು</p></div></div></div></div></div></section><section class="section-beige"><div class="container"><p class="eyebrow">ಒಳಾಂಗಣ</p><h2>ಮೂರು ಆರಾಮದಾಯಕ ಮಲಗುವ ಕೋಣೆಗಳು ಮತ್ತು ಸಾಮಾನ್ಯ ವಾಸದ ಸ್ಥಳ.</h2><div class="grid grid-3">{ROOMCARDS}</div></div></section><section><div class="container"><p class="eyebrow">ತಿಳಿದುಕೊಳ್ಳಿ</p><h2>ಸರಳ, ನೇರ ವಿಚಾರಣೆ.</h2><p>ಕೊಠಡಿ ಆಯ್ಕೆ ಮಾಡುವ ಅಗತ್ಯವಿಲ್ಲ. ನಿಮ್ಮ ದಿನಾಂಕ ಮತ್ತು ಅತಿಥಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ತಿಳಿಸಿ; ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ಕುರಿತು ವಿಚಾರಿಸಿ.</p><div class="hero-ctas"><a href="contact.html" class="btn btn-primary">ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a><a href="#" data-cta="whatsapp" class="btn btn-whatsapp">ವಾಟ್ಸ್ಆಪ್‌ನಲ್ಲಿ ವಿಚಾರಿಸಿ</a></div></div></section>'''),
'about.html':('ನಮ್ಮ ಬಗ್ಗೆ | The Coorg Chimm’s Camptime Homestay','ಕೊಡಗಿನ ಉಲುಗುಳಿಯ ಕಾಫಿ ತೋಟಗಳ ನಡುವೆ ಇರುವ The Coorg Chimm’s Camptime Homestay ಕುರಿತು ತಿಳಿಯಿರಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ನಮ್ಮ ಬಗ್ಗೆ</p><h1>ಕೊಡಗಿನ ಮಣ್ಣಿನ ಸೊಗಡಿನ ನಡುವೆ ಒಂದು ನೆಮ್ಮದಿಯ ಮನೆ.</h1><p>ನಗರದ ಗದ್ದಲದಿಂದ ಸ್ವಲ್ಪ ದೂರ, ಕುಟುಂಬ ಮತ್ತು ಸ್ನೇಹಿತರೊಂದಿಗೆ ನಿಧಾನವಾಗಿ ಕಾಲ ಕಳೆಯಲು ರೂಪುಗೊಂಡ ವಾಸ್ತವ್ಯ.</p></div></section><section><div class="container"><div class="split"><div class="split-copy"><p class="eyebrow">ಉಲುಗುಳಿಯ ನಮ್ಮ ಮನೆ</p><h2>ಕಾಫಿ ತೋಟಗಳ ಹಸಿರಿನಲ್ಲಿ ನೆಲೆಸಿರುವ ತಾಣ.</h2><p>ಉಲುಗುಳಿ ಗ್ರಾಮದ ಸುತ್ತಲಿನ ಕಾಫಿ ತೋಟಗಳು ಮತ್ತು ಮಲೆನಾಡಿನ ಹಸಿರು ಈ ಸ್ಥಳದ ನೈಸರ್ಗಿಕ ಹಿನ್ನೆಲೆ. ಇಲ್ಲಿ ಬೆಳಗಿನ ಸಮಯ ಮಂಜಿನಿಂದ ಆರಂಭವಾಗಿ, ಸಂಜೆ ಮೌನದಲ್ಲಿ ಕರಗುತ್ತದೆ.</p><p>ಸಂಪೂರ್ಣ ಆಸ್ತಿಯನ್ನು ಒಂದೇ ಘಟಕವಾಗಿ ನೀಡುವುದರಿಂದ ಕುಟುಂಬಗಳು ಮತ್ತು ಸ್ನೇಹಿತರ ಗುಂಪುಗಳು ತಮ್ಮದೇ ವೇಗದಲ್ಲಿ ಸಮಯ ಕಳೆಯಬಹುದು.</p></div>{IMG('coorg-homestay-entrance-greenery.webp','ಉಲುಗುಳಿಯ ಹೋಂಸ್ಟೇ ಪ್ರವೇಶದ್ವಾರ ಮತ್ತು ಹಸಿರು','tall')}</div></div></section><section class="section-beige"><div class="container"><div class="split"><div class="split-copy"><p class="eyebrow">ಆತಿಥ್ಯ</p><h2>ಸರಳತೆ, ನೆಮ್ಮದಿ ಮತ್ತು ಒಟ್ಟಾಗಿ ಕಳೆಯುವ ಸಮಯ.</h2><p>ಇದು ದೊಡ್ಡ ರೆಸಾರ್ಟ್‌ನ ಗದ್ದಲಕ್ಕಿಂತ ವಿಭಿನ್ನವಾದ, ಚಿಕ್ಕದಾದ ಮತ್ತು ವೈಯಕ್ತಿಕ ನೆಲೆ. ದಿನದ ಪ್ರವಾಸ ಮುಗಿಸಿ ಮರಳಿದಾಗ ನಿಮ್ಮ ಗುಂಪಿನೊಂದಿಗೆ ಕುಳಿತುಕೊಳ್ಳಲು ಒಂದು ಮನೆಯಂತಿರುವ ಜಾಗ.</p></div>{IMG('coorg-homestay-living-room.webp','ಹೋಂಸ್ಟೇಯ ಸಾಮಾನ್ಯ ವಾಸದ ಸ್ಥಳ','tall')}</div></div></section>'''),
'gallery.html':('ಚಿತ್ರಗಳ ಗ್ಯಾಲರಿ | The Coorg Chimm’s Camptime Homestay','ಕೊಡಗಿನ The Coorg Chimm’s Camptime Homestay ನ ಹೊರಾಂಗಣ, ಮಲಗುವ ಕೋಣೆಗಳು ಮತ್ತು ಸಾಮಾನ್ಯ ಸ್ಥಳಗಳ ಚಿತ್ರಗಳನ್ನು ನೋಡಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಚಿತ್ರಗಳ ಗ್ಯಾಲರಿ</p><h1>ನಿಮ್ಮ ವಾಸ್ತವ್ಯದ ಒಂದು ನೋಟ.</h1><p>ನಿಜವಾದ ಆಸ್ತಿಯ ಚಿತ್ರಗಳ ಮೂಲಕ ಹೋಂಸ್ಟೇಯ ವಾತಾವರಣವನ್ನು ಮುಂಚಿತವಾಗಿಯೇ ಅನುಭವಿಸಿ.</p></div></section><section><div class="container"><div class="masonry">{GALLERY}</div></div></section><section class="text-center"><div class="container"><h2>ಇಷ್ಟವಾಯಿತೇ?</h2><p>ನಿಮ್ಮ ದಿನಾಂಕ ಮತ್ತು ಅತಿಥಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ಕಳುಹಿಸಿ.</p><div class="hero-ctas" style="justify-content:center;"><a href="contact.html" class="btn btn-primary">ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a><a href="#" data-cta="whatsapp" class="btn btn-whatsapp">ವಾಟ್ಸ್ಆಪ್</a></div></div></section>'''),
'things-to-do.html':('ಸೂಂಟಿಕೊಪ್ಪ ಮತ್ತು ಕೊಡಗಿನ 10 ಪ್ರವಾಸ ತಾಣಗಳು','The Coorg Chimm’s Camptime Homestay ನಿಂದ ಅಂದಾಜು ಪ್ರಯಾಣ ಸಮಯದೊಂದಿಗೆ ಕೊಡಗಿನ ಜನಪ್ರಿಯ ತಾಣಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಸುತ್ತಮುತ್ತ ಅನ್ವೇಷಿಸಿ</p><h1>ಸೂಂಟಿಕೊಪ್ಪ ಮತ್ತು ಕೊಡಗಿನ ನೆನಪಿನಲ್ಲಿ ಉಳಿಯುವ 10 ತಾಣಗಳು.</h1><p>ಕಾಫಿ ಅನುಭವಗಳಿಂದ ಜಲಪಾತ, ಬೆಟ್ಟ, ನದಿ ಮತ್ತು ಸಂಸ್ಕೃತಿವರೆಗೆ — ನಿಮ್ಮ ದಿನದ ಪ್ರವಾಸಕ್ಕೆ ಆಯ್ಕೆ ಮಾಡಿಕೊಳ್ಳಬಹುದಾದ ತಾಣಗಳು.</p></div></section><section><div class="container"><div class="grid grid-3">{ATTRACTIONS}</div></div></section><section class="section-beige"><div class="container"><p class="eyebrow">ನಿಮ್ಮ ನೆಲೆ</p><h2>ಸೂಂಟಿಕೊಪ್ಪದ ಬಳಿ ಇರುವ ಶಾಂತವಾದ ನೆಲೆ.</h2><p class="max-w-prose">ಹೋಂಸ್ಟೇ ಉಲುಗುಳಿ ಗ್ರಾಮದಲ್ಲಿ, ಸೂಂಟಿಕೊಪ್ಪದ ಸಮೀಪದಲ್ಲಿದೆ. ಕೆಳಗಿನ ಸಮಯಗಳು ಅಂದಾಜು ಚಾಲನಾ ಸಮಯಗಳು; ಸಂಚಾರ ಮತ್ತು ರಸ್ತೆಯ ಪರಿಸ್ಥಿತಿಗೆ ಅನುಗುಣವಾಗಿ ಬದಲಾಗಬಹುದು.</p><div class="hero-ctas"><a href="location.html" class="btn btn-forest">ಸ್ಥಳ ನೋಡಿ</a><a href="contact.html" class="btn btn-ghost">ವಾಸ್ತವ್ಯ ಯೋಜಿಸಿ</a></div></div></section>'''),
'location.html':('ಸ್ಥಳ ಮತ್ತು ದಾರಿ | Uluguli, Suntikoppa, Coorg','The Coorg Chimm’s Camptime Homestay, Uluguli, Suntikoppa, Kodagu ಗೆ ದಾರಿ ಮತ್ತು ಸ್ಥಳದ ಮಾಹಿತಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಸ್ಥಳ</p><h1>ಉಲುಗುಳಿಯಲ್ಲಿ, ಸೂಂಟಿಕೊಪ್ಪದ ಸಮೀಪ ನಮ್ಮನ್ನು ಕಂಡುಕೊಳ್ಳಿ.</h1><p>ಕೊಡಗು ಜಿಲ್ಲೆಯ ಉಲುಗುಳಿ ಗ್ರಾಮದ ಹಸಿರಿನ ನಡುವೆ, ಕಾಫಿ ತೋಟಗಳ ಸುತ್ತಮುತ್ತ ಇರುವ ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ.</p></div></section><section><div class="container"><div class="split"><div><p class="eyebrow">ವಿಳಾಸ</p><h2>ದಿ ಕೂರ್ಗ್ ಚಿಮ್ಮ್ಸ್ ಕ್ಯಾಂಪ್‌ಟೈಮ್ ಹೋಂಸ್ಟೇ</h2><p>Gaddehalla, Uluguli Village, Suntikoppa, Kodagu, Karnataka 571237, India</p><p><strong>ಫೋನ್:</strong> <a href="#" data-cta="call">+91 99726 26256</a></p><div class="hero-ctas"><a href="#" data-cta="maps" class="btn btn-primary">ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್ ತೆರೆಯಿರಿ</a><a href="#" data-cta="call" class="btn btn-ghost">ಕರೆ ಮಾಡಿ</a></div></div><div class="map-embed"><iframe title="The Coorg Chimm's Camptime Homestay location map" src="https://www.google.com/maps?q=The%20Coorg%20Chimm%27s%20Camptime%20Homestay%2C%20Uluguli%2C%20Suntikoppa%2C%20Karnataka&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></div></div></section><section class="section-beige"><div class="container"><p class="eyebrow">ಹತ್ತಿರದ ಪ್ರದೇಶಗಳು</p><h2>ಕೊಡಗನ್ನು ಸುತ್ತಲು ಅನುಕೂಲಕರ ನೆಲೆ.</h2><div class="grid grid-3"><div class="card"><div class="card-body"><h3>ಸೂಂಟಿಕೊಪ್ಪ</h3><p>ಸ್ಥಳೀಯ ಪಟ್ಟಣ ಮತ್ತು ದೈನಂದಿನ ಅಗತ್ಯಗಳಿಗೆ ಹತ್ತಿರದ ಪ್ರದೇಶ.</p></div></div><div class="card"><div class="card-body"><h3>ಮಡಿಕೇರಿ</h3><p>ಜಿಲ್ಲಾ ಕೇಂದ್ರ; ಕೋಟೆ, ರಾಜಾಸೀಟ್ ಮತ್ತು ನಗರದ ಪ್ರಮುಖ ತಾಣಗಳಿಗೆ ದಾರಿ.</p></div></div><div class="card"><div class="card-body"><h3>ಕುಶಾಲನಗರ</h3><p>ಕಾವೇರಿ ತೀರ, ನಿಸರ್ಗಧಾಮ ಮತ್ತು ಬೈಲಕುಪ್ಪೆಯತ್ತ ಹೋಗಲು ಅನುಕೂಲಕರ ದಿಕ್ಕು.</p></div></div></div></div></section>'''),
'contact.html':('ಸಂಪರ್ಕಿಸಿ ಮತ್ತು ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ | Coorg Homestay','ಕೊಡಗಿನ ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ಕುರಿತು ದಿನಾಂಕ ಮತ್ತು ಅತಿಥಿಗಳ ಸಂಖ್ಯೆಯೊಂದಿಗೆ ವಿಚಾರಿಸಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಸಂಪರ್ಕಿಸಿ</p><h1>ನಿಮ್ಮ ಕೊಡಗು ವಾಸ್ತವ್ಯವನ್ನು ಯೋಜಿಸೋಣ.</h1><p>ದಿನಾಂಕ, ಅತಿಥಿಗಳ ಸಂಖ್ಯೆ ಮತ್ತು ನಿಮ್ಮ ಅಗತ್ಯಗಳನ್ನು ಕಳುಹಿಸಿ.</p></div></section><section><div class="container"><div class="split"><div><p class="eyebrow">ವಾಸ್ತವ್ಯ ವಿಚಾರಣೆ</p><h2>ನಿಮ್ಮ ದಿನಾಂಕಗಳನ್ನು ಕಳುಹಿಸಿ.</h2><form id="enquiry-form"><div class="form-grid cols-2"><div class="field"><label for="name">ಹೆಸರು</label><input id="name" name="name" required></div><div class="field"><label for="phone">ಫೋನ್</label><input id="phone" name="phone" required></div><div class="field"><label for="email">ಇಮೇಲ್</label><input id="email" name="email" type="email"></div><div class="field"><label for="guests">ಅತಿಥಿಗಳು</label><input id="guests" name="guests" type="number" min="4" max="12" required></div><div class="field"><label for="checkin">ಬರುವ ದಿನಾಂಕ</label><input id="checkin" name="checkin" type="date" required></div><div class="field"><label for="checkout">ಹೊರಡುವ ದಿನಾಂಕ</label><input id="checkout" name="checkout" type="date" required></div></div><div class="field"><label for="message">ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ <span class="hint">(ನಿಮ್ಮ ಅಗತ್ಯಗಳು)</span></label><textarea id="message" name="message"></textarea></div><button class="btn btn-primary" type="submit">ವಾಟ್ಸ್ಆಪ್ ಮೂಲಕ ವಿಚಾರಣೆ ಕಳುಹಿಸಿ</button><p id="form-status" class="form-note" hidden></p></form></div><div><p class="eyebrow">ನೇರ ಸಂಪರ್ಕ</p><h2>ತಕ್ಷಣ ಮಾತನಾಡಿ.</h2><p><a href="#" data-cta="call">+91 99726 26256</a></p><p><a href="#" data-cta="whatsapp" class="btn btn-whatsapp">ವಾಟ್ಸ್ಆಪ್‌ನಲ್ಲಿ ಮಾತಾಡಿ</a></p><p><strong>ವಿಳಾಸ</strong><br>Gaddehalla, Uluguli Village,<br>Suntikoppa, Kodagu,<br>Karnataka 571237, India</p></div></div></div></section>'''),
'how-to-reach.html':('ಕೊಡಗಿಗೆ ಹೇಗೆ ತಲುಪುವುದು? | ರಸ್ತೆ, ರೈಲು ಮತ್ತು ವಿಮಾನ','ಕೊಡಗಿನ ಉಲುಗುಳಿಯ The Coorg Chimm’s Camptime Homestay ಗೆ ರಸ್ತೆ, ರೈಲು ಮತ್ತು ವಿಮಾನದ ಮೂಲಕ ತಲುಪುವ ಮಾರ್ಗಗಳು.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಹೇಗೆ ತಲುಪುವುದು?</p><h1>ರಸ್ತೆ, ರೈಲು ಅಥವಾ ವಿಮಾನ — ಕೊಡಗಿನತ್ತ ನಿಮ್ಮ ಪ್ರಯಾಣ.</h1><p>ಸೂಂಟಿಕೊಪ್ಪದ ಸಮೀಪದ ಉಲುಗುಳಿಯ ಹೋಂಸ್ಟೇಗೆ ತಲುಪಲು ಸಾಮಾನ್ಯ ಮಾರ್ಗಗಳು.</p></div></section><section><div class="container"><div class="grid grid-2"><article class="card"><div class="card-body"><h2>ವಿಮಾನದಲ್ಲಿ</h2><p>ಕಣ್ಣೂರು ಅಂತಾರಾಷ್ಟ್ರೀಯ ವಿಮಾನ ನಿಲ್ದಾಣವು ಕೊಡಗಿನ ಈ ಭಾಗಕ್ಕೆ ಉಪಯುಕ್ತ ಆಯ್ಕೆ. ಮೈಸೂರು ಮತ್ತು ಮಂಗಳೂರು ವಿಮಾನ ನಿಲ್ದಾಣಗಳೂ ಪ್ರಯಾಣ ಯೋಜನೆಗೆ ಅನುಗುಣವಾಗಿ ಪರ್ಯಾಯಗಳಾಗಿವೆ.</p></div></article><article class="card"><div class="card-body"><h2>ರೈಲಿನಲ್ಲಿ</h2><p>ಕೊಡಗಿನಲ್ಲಿ ರೈಲು ನಿಲ್ದಾಣವಿಲ್ಲ. ಮೈಸೂರು ಅಥವಾ ಮಂಗಳೂರು ಭಾಗದ ರೈಲು ನಿಲ್ದಾಣ ತಲುಪಿ ಅಲ್ಲಿಂದ ರಸ್ತೆ ಮೂಲಕ ಮುಂದುವರಿಯುವುದು ಸಾಮಾನ್ಯ ಮಾರ್ಗ.</p></div></article><article class="card"><div class="card-body"><h2>ರಸ್ತೆಯಲ್ಲಿ</h2><p>ಕೊಡಗಿಗೆ ರಸ್ತೆ ಸಂಪರ್ಕ ಉತ್ತಮವಾಗಿದೆ. ನಿಮ್ಮ ಪ್ರಾರಂಭಿಕ ನಗರದಿಂದ ಸೂಂಟಿಕೊಪ್ಪದತ್ತ ಮಾರ್ಗ ಯೋಜಿಸಿ, ನಂತರ ಉಲುಗುಳಿ ಗ್ರಾಮದ ಹೋಂಸ್ಟೇಗೆ ಬನ್ನಿ.</p></div></article><article class="card"><div class="card-body"><h2>ಹೋಂಸ್ಟೇ ತಲುಪಿದಾಗ</h2><p>ಕೊನೆಯ ಹಂತಕ್ಕೆ ನಿಖರ ಸ್ಥಳವನ್ನು ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ. ರಸ್ತೆ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ಸಂಚಾರಕ್ಕೆ ಅನುಗುಣವಾಗಿ ಪ್ರಯಾಣ ಸಮಯ ಬದಲಾಗಬಹುದು.</p><a href="location.html" class="btn btn-ghost btn-sm">ಸ್ಥಳ ಮತ್ತು ದಾರಿ</a></div></article></div></div></section>'''),
'travel-guide.html':('ಕೊಡಗು ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ | ಭೇಟಿ ಮೊದಲು ತಿಳಿಯಬೇಕಾದದ್ದು','ಕೊಡಗು ಪ್ರವಾಸಕ್ಕೆ ಹವಾಮಾನ, ಸಂಚಾರ, ಕಾಫಿ ತೋಟಗಳು ಮತ್ತು ಸ್ಥಳೀಯ ಅನುಭವಗಳ ಬಗ್ಗೆ ಉಪಯುಕ್ತ ಮಾರ್ಗದರ್ಶಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಕೊಡಗು ಪ್ರವಾಸ ಮಾರ್ಗದರ್ಶಿ</p><h1>ಕೊಡಗಿಗೆ ಬರುವ ಮೊದಲು ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದ ಸಂಗತಿಗಳು.</h1><p>ಪ್ರವಾಸವನ್ನು ಗಡಿಬಿಡಿಯಿಲ್ಲದೆ ಯೋಜಿಸಿ; ನಿಮಗೆ ಬೇಕಾದ ಅನುಭವಗಳಿಗೆ ದಿನಗಳನ್ನು ಮೀಸಲಿಡಿ.</p></div></section><section><div class="container"><div class="grid grid-2"><article><h2>ಕೊಡಗು ಎಂದರೇನು?</h2><p>ಕೊಡಗು, ಅಥವಾ Coorg, ಕರ್ನಾಟಕದ ಪಶ್ಚಿಮ ಘಟ್ಟಗಳ ಹಸಿರು ಬೆಟ್ಟಗಳು ಮತ್ತು ಕಾಫಿ ತೋಟಗಳಿಗೆ ಹೆಸರುವಾಸಿಯಾದ ಪ್ರದೇಶ. ಮಡಿಕೇರಿ ಇದರ ಜಿಲ್ಲಾ ಕೇಂದ್ರ.</p></article><article><h2>ಸುತ್ತಾಡುವುದು</h2><p>ಮುಖ್ಯ ತಾಣಗಳು ಹಲವು ದಿಕ್ಕುಗಳಲ್ಲಿ ಹರಡಿರುವುದರಿಂದ ಕಾರು ಅಥವಾ ಸ್ವಂತ ವಾಹನದೊಂದಿಗೆ ದಿನದ ಪ್ರವಾಸಗಳನ್ನು ಯೋಜಿಸುವುದು ಅನುಕೂಲಕರ.</p></article><article><h2>ಹವಾಮಾನ ಮತ್ತು ಸಿದ್ಧತೆ</h2><p>ಮಳೆಗಾಲದಲ್ಲಿ ಮಳೆಸಾಧನ, ಇತರೆ ಋತುಗಳಲ್ಲಿ ಹಗುರವಾದ ಪದರದ ಬಟ್ಟೆ ಮತ್ತು ಆರಾಮದಾಯಕ ಪಾದರಕ್ಷೆಗಳನ್ನು ಹೊಂದಿರಿ.</p></article><article><h2>ಕೊಡಗಿನ ಸೊಗಡು</h2><p>ಕಾಫಿ ತೋಟಗಳು, ಜಲಪಾತಗಳು, ಬೆಟ್ಟದ ನೋಟಗಳು, ಕಾವೇರಿ ತೀರ ಮತ್ತು ವೈವಿಧ್ಯಮಯ ಸಂಸ್ಕೃತಿ ಕೊಡಗಿನ ಪ್ರವಾಸದ ಪ್ರಮುಖ ಭಾಗಗಳು.</p></article></div></div></section><section class="section-beige"><div class="container"><p class="eyebrow">ಮುಂದಿನ ಓದು</p><h2>ನಿಮ್ಮ ಪ್ರವಾಸಕ್ಕೆ ಇನ್ನಷ್ಟು ಮಾರ್ಗದರ್ಶಿಗಳು.</h2><div class="grid grid-3"><a class="card" href="things-to-do.html"><div class="card-body"><h3>10 ಪ್ರವಾಸ ತಾಣಗಳು</h3><p>ಜಲಪಾತ, ಬೆಟ್ಟ, ಕಾಫಿ, ನದಿ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಅನುಭವಗಳು.</p></div></a><a class="card" href="best-time-to-visit.html"><div class="card-body"><h3>ಭೇಟಿಗೆ ಸೂಕ್ತ ಕಾಲ</h3><p>ಋತುಗಳನ್ನು ಹೋಲಿಸಿ ನಿಮ್ಮ ಅನುಭವಕ್ಕೆ ತಕ್ಕ ಸಮಯ ಆರಿಸಿ.</p></div></a><a class="card" href="coffee-experience.html"><div class="card-body"><h3>ಕಾಫಿ ಅನುಭವ</h3><p>ಕೊಡಗಿನ ಕಾಫಿ ತೋಟಗಳ ಸೊಗಡನ್ನು ಹತ್ತಿರದಿಂದ ಅರಿಯಿರಿ.</p></div></a></div></div></section><section><div class="container"><p class="eyebrow">ಇನ್ನಷ್ಟು ಪ್ರವಾಸ ಪ್ರೇರಣೆ</p><h2>ನಮ್ಮ ಮಾರ್ಗದರ್ಶಿಗಳ ಹೊರತಾಗಿಯೂ ಉಪಯುಕ್ತ ಸಂಪನ್ಮೂಲಗಳು.</h2><p><a href="https://karnatakatourism.org/en/destinations/coorg" target="_blank" rel="noopener">ಕರ್ನಾಟಕ ಪ್ರವಾಸೋದ್ಯಮ — ಕೊಡಗು ಮಾರ್ಗದರ್ಶಿ</a></p><p><a href="https://www.holidify.com/places/coorg/sightseeing-and-things-to-do.html" target="_blank" rel="noopener">Holidify — Coorg sightseeing guide</a></p></div></section>'''),
'best-time-to-visit.html':('ಕೊಡಗುಗೆ ಭೇಟಿ ನೀಡಲು ಸೂಕ್ತ ಕಾಲ | ಋತುಗಳ ಮಾರ್ಗದರ್ಶಿ','ಕೊಡಗಿನ ಚಳಿಗಾಲ, ಬೇಸಿಗೆ ಮತ್ತು ಮಳೆಗಾಲದ ಅನುಭವಗಳನ್ನು ಹೋಲಿಸಿ ನಿಮ್ಮ ಪ್ರವಾಸಕ್ಕೆ ಸೂಕ್ತ ಸಮಯ ಆರಿಸಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಭೇಟಿಗೆ ಸೂಕ್ತ ಕಾಲ</p><h1>ಕೊಡಗಿನ ಋತುವನ್ನು ನಿಮ್ಮ ಅನುಭವಕ್ಕೆ ತಕ್ಕಂತೆ ಆರಿಸಿ.</h1><p>ಪ್ರತಿ ಋತುವಿಗೂ ತನ್ನದೇ ಆದ ಬಣ್ಣ, ವಾಸನೆ ಮತ್ತು ವಾತಾವರಣವಿದೆ.</p></div></section><section><div class="container"><div class="grid grid-3"><article><h2>ಚಳಿಗಾಲ · ಅಕ್ಟೋಬರ್–ಫೆಬ್ರವರಿ</h2><p>ತಂಪಾದ ಬೆಳಗ್ಗೆ, ಆರಾಮದಾಯಕ ದಿನಗಳು ಮತ್ತು ಹೊರಾಂಗಣ ಪ್ರವಾಸಕ್ಕೆ ಜನಪ್ರಿಯ ಕಾಲ.</p></article><article><h2>ಬೇಸಿಗೆ · ಮಾರ್ಚ್–ಮೇ</h2><p>ನಗರದ ಬಿಸಿಯಿಂದ ತಪ್ಪಿಸಿಕೊಂಡು ಮಲೆನಾಡಿನ ಹಸಿರು ಮತ್ತು ತಂಪನ್ನು ಅನುಭವಿಸಲು ಸೂಕ್ತ.</p></article><article><h2>ಮಳೆಗಾಲ · ಜೂನ್–ಸೆಪ್ಟೆಂಬರ್</h2><p>ಮಳೆ, ಮಂಜು ಮತ್ತು ತುಂಬಿ ಹರಿಯುವ ಹಸಿರು ಪ್ರಕೃತಿ; ಮಳೆಯ ವಾತಾವರಣ ಇಷ್ಟಪಡುವವರಿಗೆ ವಿಶಿಷ್ಟ ಅನುಭವ.</p></article></div></div></section><section class="section-beige"><div class="container"><p class="eyebrow">ನಮ್ಮ ಅಭಿಪ್ರಾಯ</p><h2>ಹೋಂಸ್ಟೇ ವಾಸ್ತವ್ಯಕ್ಕೆ ಒಂದೇ ಸರಿಯಾದ ಋತು ಇಲ್ಲ.</h2><p>ನೀವು ಬಯಸುವ ಕೊಡಗಿನ ಚಿತ್ರವನ್ನು ಆರಿಸಿ — ಮಂಜಿನ ಬೆಳಗ್ಗೆ, ಹಸಿರು ಮಳೆ, ಅಥವಾ ತಂಪಾದ ಚಳಿಗಾಲದ ಪ್ರವಾಸ.</p><div class="hero-ctas"><a href="things-to-do.html" class="btn btn-primary">ತಾಣಗಳನ್ನು ನೋಡಿ</a><a href="contact.html" class="btn btn-ghost">ವಾಸ್ತವ್ಯ ವಿಚಾರಿಸಿ</a></div></div></section>'''),
'coffee-experience.html':('ಕೊಡಗಿನ ಕಾಫಿ ಅನುಭವ | ಕಾಫಿ ತೋಟಗಳ ಮಾರ್ಗದರ್ಶಿ','ಕೊಡಗಿನ ಕಾಫಿ ತೋಟಗಳು, ತೋಟದ ಅನುಭವ ಮತ್ತು ಕಾಫಿಯ ಸೊಗಡನ್ನು ಅರಿಯಲು ಒಂದು ಸರಳ ಮಾರ್ಗದರ್ಶಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಕೊಡಗಿನ ಕಾಫಿ ಅನುಭವ</p><h1>ಕಾಫಿಯ ನಾಡನ್ನು ಹತ್ತಿರದಿಂದ ಅನುಭವಿಸಿ.</h1><p>ಕೊಡಗಿನ ಗುರುತಿನೊಂದಿಗೆ ಬೆಸೆದುಕೊಂಡಿರುವ ಕಾಫಿ ತೋಟಗಳ ಹಸಿರು, ಪರಿಮಳ ಮತ್ತು ನಿಧಾನಗತಿಯ ಜೀವನವನ್ನು ಅರಿಯಿರಿ.</p></div></section><section><div class="container"><div class="split"><div class="split-copy"><p class="eyebrow">ಕಾಫಿ ಏಕೆ ಇಲ್ಲಿಗೆ ಸೂಕ್ತ?</p><h2>ಬೆಟ್ಟ, ಮಳೆ ಮತ್ತು ಹಸಿರು — ಕಾಫಿಗೆ ತಕ್ಕ ನೆಲೆ.</h2><p>ಕೊಡಗಿನ ಕಾಫಿ ತೋಟಗಳು ಈ ಪ್ರದೇಶದ ದೃಶ್ಯ ಮತ್ತು ಜೀವನಶೈಲಿಯ ಭಾಗವಾಗಿವೆ. ತೋಟದ ದಾರಿಗಳಲ್ಲಿ ನಡೆಯುವಾಗ ಕಾಫಿ ಗಿಡಗಳ ಸಾಲು, ಮರಗಳ ನೆರಳು ಮತ್ತು ಮಣ್ಣಿನ ವಾಸನೆ ಅನುಭವಿಸಬಹುದು.</p></div>{IMG('places/coffee-plantations.svg','ಕೊಡಗಿನ ಕಾಫಿ ತೋಟಗಳ ಚಿತ್ರ','tall')}</div></div></section><section class="section-beige"><div class="container"><h2>ತೋಟದ ಭೇಟಿ ಹೇಗಿರಬಹುದು?</h2><p>ಮಾರ್ಗದರ್ಶಿತ ತೋಟ ಪ್ರವಾಸಗಳಲ್ಲಿ ಕಾಫಿ ಬೆಳೆ, ಕೊಯ್ಲು ಮತ್ತು ಸಂಸ್ಕರಣೆಯ ಬಗ್ಗೆ ತಿಳಿದುಕೊಳ್ಳಬಹುದು. ಸ್ಥಳೀಯ ಅನುಭವದ ಲಭ್ಯತೆ ಋತು ಮತ್ತು ಆಯೋಜಕರ ಮೇಲೆ ಅವಲಂಬಿತ.</p><h2>ನಿಮ್ಮ ನೆಲೆ — ಚಿಮ್ಮ್ಸ್ ಕ್ಯಾಂಪ್‌ಟೈಮ್</h2><p>ತೋಟಗಳ ಹಸಿರಿನ ನಡುವೆ ದಿನ ಮುಗಿಸಿ, ಮತ್ತೆ ಹೋಂಸ್ಟೇಯ ನೆಮ್ಮದಿಗೆ ಮರಳುವುದು ಈ ಪ್ರದೇಶದ ಸೊಗಡನ್ನು ಅನುಭವಿಸುವ ಸರಳ ವಿಧಾನ.</p></div></section>'''),
'privacy-policy.html':('ಗೌಪ್ಯತಾ ನೀತಿ | The Coorg Chimm’s Camptime Homestay','ಈ ಸ್ಥಿರ ವೆಬ್‌ಸೈಟ್ ಬಳಕೆದಾರರ ಮಾಹಿತಿಯನ್ನು ಹೇಗೆ ನಿರ್ವಹಿಸುತ್ತದೆ ಎಂಬುದರ ಸರಳ ಗೌಪ್ಯತಾ ಮಾಹಿತಿ.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ಗೌಪ್ಯತಾ ನೀತಿ</p><h1>ನಿಮ್ಮ ಗೌಪ್ಯತೆಗೆ ಗೌರವ.</h1></div></section><section><div class="container max-w-prose"><h2>ಈ ತಾಣದ ಕುರಿತು</h2><p>ಈ ವೆಬ್‌ಸೈಟ್ The Coorg Chimm’s Camptime Homestay ಕುರಿತು ಮಾಹಿತಿ ನೀಡುತ್ತದೆ. ಪ್ರಸ್ತುತ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಯಾವುದೇ ಸ್ವಂತ ಸರ್ವರ್ ಅಥವಾ ಡೇಟಾಬೇಸ್‌ಗೆ ಫಾರ್ಮ್ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸುವ ವ್ಯವಸ್ಥೆ ಇಲ್ಲ.</p><h2>ವಿಚಾರಣೆ</h2><p>ವಿಚಾರಣೆ ಫಾರ್ಮ್‌ನ ವಿವರಗಳನ್ನು ಬಳಕೆದಾರರ ಅನುಮತಿಯಿಂದ WhatsApp ಮೂಲಕ ಕಳುಹಿಸಲು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತದೆ.</p><h2>ಕುಕೀಗಳು</h2><p>ಭಾಷಾ ಆಯ್ಕೆಯನ್ನು ನೆನಪಿಡಲು ಈ ತಾಣವು ಅಗತ್ಯವಾದ ಭಾಷಾ ಆದ್ಯತಾ ಕುಕಿಯನ್ನು ಬಳಸಬಹುದು.</p><h2>ಮುಂದಿನ ಬದಲಾವಣೆಗಳು</h2><p>ಹೊಸ analytics, advertising ಅಥವಾ booking ಸೇವೆಗಳನ್ನು ಸೇರಿಸಿದರೆ ಈ ನೀತಿಯನ್ನು ಅದಕ್ಕೆ ಅನುಗುಣವಾಗಿ ನವೀಕರಿಸಲಾಗುತ್ತದೆ.</p></div></section>'''),
'terms.html':('ನಿಯಮಗಳು | The Coorg Chimm’s Camptime Homestay','The Coorg Chimm’s Camptime Homestay ವೆಬ್‌ಸೈಟ್ ಬಳಕೆಗೆ ಸಾಮಾನ್ಯ ನಿಯಮಗಳು.','''<section class="page-hero"><div class="container"><p class="eyebrow" style="color:var(--beige-100);">ನಿಯಮಗಳು</p><h1>ಈ ತಾಣವನ್ನು ಬಳಸುವಾಗ ತಿಳಿದುಕೊಳ್ಳಬೇಕಾದವು.</h1></div></section><section><div class="container max-w-prose"><h2>ಮಾಹಿತಿ</h2><p>ಈ ತಾಣದಲ್ಲಿರುವ ಪ್ರವಾಸ ಮಾಹಿತಿ ಮತ್ತು ಅಂದಾಜು ಪ್ರಯಾಣ ಸಮಯಗಳು ಮಾರ್ಗದರ್ಶನಕ್ಕಾಗಿ ಮಾತ್ರ. ರಸ್ತೆ, ಹವಾಮಾನ ಮತ್ತು ಸ್ಥಳೀಯ ಪರಿಸ್ಥಿತಿಗಳಿಂದ ಸಮಯ ಬದಲಾಗಬಹುದು.</p><h2>ಬುಕಿಂಗ್</h2><p>ಹೋಂಸ್ಟೇಯನ್ನು ಸಂಪೂರ್ಣ ಆಸ್ತಿಯಾಗಿ ಮಾತ್ರ ಕಾಯ್ದಿರಿಸಲಾಗುತ್ತದೆ. ಬುಕಿಂಗ್, ಪಾವತಿ ಮತ್ತು ರದ್ದತಿ ಷರತ್ತುಗಳನ್ನು ಆಸ್ತಿಯೊಂದಿಗೆ ನೇರವಾಗಿ ದೃಢಪಡಿಸಬೇಕು.</p><h2>ಚಿತ್ರಗಳು</h2><p>ಆಸ್ತಿಯ ಚಿತ್ರಗಳು ಮಾಲೀಕರಿಂದ ಒದಗಿಸಲಾದವು; ಸ್ಥಳಗಳಿಗಾಗಿ ಬಳಸುವ ದೃಶ್ಯ ಸಂಪನ್ಮೂಲಗಳಿಗೆ ಅನ್ವಯಿಸುವ ಮೂಲ/ಪರವಾನಗಿ ಮಾಹಿತಿಯನ್ನು ಯೋಜನಾ ದಾಖಲೆಗಳಲ್ಲಿ ನಿರ್ವಹಿಸಲಾಗುತ್ತದೆ.</p></div></section>''')}

def IMG(src,alt,cls='ratio-16-9'): return f'<div class="img-ph {cls}"><img src="../images/{src}" alt="{alt}" loading="lazy" decoding="async"></div>'

# Replace tokens
roomcards=''.join([IMG('coorg-homestay-bedroom-purple.webp','ಹೋಂಸ್ಟೇಯ ಮಲಗುವ ಕೋಣೆ 1')+'<h3>ಮಲಗುವ ಕೋಣೆ 1</h3><p>ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ವಾಸ್ತವ್ಯದ ಭಾಗ.</p>',IMG('coorg-homestay-bedroom-blue.webp','ಹೋಂಸ್ಟೇಯ ಮಲಗುವ ಕೋಣೆ 2')+'<h3>ಮಲಗುವ ಕೋಣೆ 2</h3><p>ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ವಾಸ್ತವ್ಯದ ಭಾಗ.</p>',IMG('coorg-homestay-bedroom-3.webp','ಹೋಂಸ್ಟೇಯ ಮಲಗುವ ಕೋಣೆ 3')+'<h3>ಮಲಗುವ ಕೋಣೆ 3</h3><p>ಸಂಪೂರ್ಣ ಹೋಂಸ್ಟೇ ವಾಸ್ತವ್ಯದ ಭಾಗ.</p>'])
gallery=''.join([IMG(s,a) for s,a in [('coorg-homestay-hero.webp','ಹೋಂಸ್ಟೇ ಹೊರಾಂಗಣ'),('coorg-homestay-entrance-greenery.webp','ಹೋಂಸ್ಟೇ ಪ್ರವೇಶ ಮತ್ತು ಹಸಿರು'),('coorg-homestay-property.webp','ಹೋಂಸ್ಟೇ ಮುಂಭಾಗ'),('coorg-homestay-bedroom-blue.webp','ನೀಲಿ ಅಲಂಕಾರದ ಮಲಗುವ ಕೋಣೆ'),('coorg-homestay-bedroom-purple.webp','ಮಲಗುವ ಕೋಣೆ'),('coorg-homestay-bedroom-3.webp','ಮೂರನೇ ಮಲಗುವ ಕೋಣೆ'),('coorg-homestay-bedroom-red.webp','ಮಲಗುವ ಕೋಣೆ ಮತ್ತು ಕೊಡಗಿನ ಚಿತ್ರಗಳು'),('coorg-homestay-living-room.webp','ಸಾಮಾನ್ಯ ವಾಸದ ಸ್ಥಳ'),('coorg-homestay-common-area.webp','ಸಾಮಾನ್ಯ ಪ್ರದೇಶ'),('coorg-homestay-washroom.webp','ಸ್ನಾನಗೃಹ')]])
attrs=[('coffee-plantations.svg','ಕೊಡಗಿನ ಕಾಫಿ ತೋಟ','ಕಾಫಿ ಮತ್ತು ಪ್ರಕೃತಿ','Greenway Coffee Island Plantation Tour','ಕಾಫಿ ತೋಟದ ವಾತಾವರಣ ಮತ್ತು ಪ್ರಕೃತಿಯನ್ನು ಹತ್ತಿರದಿಂದ ಅನುಭವಿಸಲು ಸಮೀಪದ ಆಯ್ಕೆ.','11'),('nisargadhama.svg','ಕಾವೇರಿ ನಿಸರ್ಗಧಾಮ','ಪ್ರಕೃತಿ','Kaveri Nisargadhama','ಕಾವೇರಿ ನದಿಯ ಮೇಲಿನ ಹಸಿರು ದ್ವೀಪ; ನಿಧಾನವಾದ ಪ್ರಕೃತಿ ವಿಹಾರಕ್ಕೆ ಸೂಕ್ತ.','22'),('chiklihole-reservoir.svg','ಚಿಕ್ಲಿಹೊಳೆ ಜಲಾಶಯ','ದೃಶ್ಯ ತಾಣ','Chiklihole Reservoir','ಹಸಿರಿನಿಂದ ಸುತ್ತುವರಿದ ಶಾಂತ ಜಲಾಶಯ; ದೃಶ್ಯ ಮತ್ತು ಛಾಯಾಗ್ರಹಣಕ್ಕೆ ಸೂಕ್ತ.','24'),('rajas-seat.svg','ರಾಜಾಸೀಟ್','ವೀಕ್ಷಣಾ ತಾಣ','Raja’s Seat','ಮಡಿಕೇರಿಯ ಪ್ರಸಿದ್ಧ ನೋಟದ ತಾಣ; ಬೆಟ್ಟ ಮತ್ತು ಕಣಿವೆಗಳ ವಿಶಾಲ ದೃಶ್ಯ.','25'),('madikeri-fort.svg','ಮಡಿಕೇರಿ ಕೋಟೆ','ಪರಂಪರೆ','Madikeri Fort','ಮಡಿಕೇರಿಯ ಇತಿಹಾಸದ ಪ್ರಮುಖ ಗುರುತು ಮತ್ತು ನಗರ ಪ್ರವಾಸದ ಭಾಗ.','25'),('harangi-reservoir.svg','ಹಾರಂಗಿ ಜಲಾಶಯ','ನೀರು ಮತ್ತು ಪ್ರಕೃತಿ','Harangi Reservoir / Backwaters','ನೀರು, ಹಸಿರು ಮತ್ತು ಶಾಂತ ದೃಶ್ಯಗಳಿಗಾಗಿ ಒಂದು ದಿನದ ಪ್ರವಾಸದ ಆಯ್ಕೆ.','31–32'),('abbey-falls.svg','ಅಬ್ಬೆ ಜಲಪಾತ','ಜಲಪಾತ','Abbey Falls','ಕಾಫಿ ಮತ್ತು ಮಸಾಲೆ ತೋಟಗಳ ನಡುವೆ ಇರುವ ಜನಪ್ರಿಯ ಜಲಪಾತ.','33'),('dubare-elephant-camp.svg','ದುಬಾರೆ ಆನೆ ಶಿಬಿರ','ಸಾಹಸ','Dubare Elephant Camp','ಕಾವೇರಿ ತೀರದ ಪ್ರಕೃತಿ ಮತ್ತು ಆನೆಗಳ ಅನುಭವಕ್ಕೆ ಪ್ರಸಿದ್ಧ ತಾಣ.','35'),('golden-temple.svg','ನಮ್ದ್ರೋಲಿಂಗ್ ಮಠ / ಗೋಲ್ಡನ್ ಟೆಂಪಲ್','ಸಂಸ್ಕೃತಿ','Namdroling Monastery / Golden Temple','ಬೈಲಕುಪ್ಪೆಯ ಪ್ರಸಿದ್ಧ ಟಿಬೆಟಿಯನ್ ಬೌದ್ಧ ಮಠ ಮತ್ತು ಚಿನ್ನದ ಪ್ರತಿಮೆಗಳ ತಾಣ.','36'),('mandalpatti.svg','ಮಂಡಲ್ಪಟ್ಟಿ ಶಿಖರ','ಬೆಟ್ಟಗಳು','Mandalpatti Peak','ಮಂಜು, ಬೆಟ್ಟಗಳ ವಿಶಾಲ ನೋಟ ಮತ್ತು 4x4 ಮಾರ್ಗಗಳಿಗೆ ಜನಪ್ರಿಯ ಎತ್ತರದ ತಾಣ.','1 ಗಂ. 21 ನಿ.')]
attractions=''.join([f'<article class="card"><div class="img-ph ratio-16-9"><img src="../images/places/{p}" alt="{alt}" loading="lazy" decoding="async"></div><div class="card-body"><span class="tag">{tag}</span><h2 style="font-size:1.35rem;margin-top:.65rem;">{name}</h2><p>{d}</p><p style="font-size:.85rem;color:var(--ink-700);font-weight:600;">ಅಂದಾಜು {mins} ನಿಮಿಷಗಳ ಪ್ರಯಾಣ</p><a href="https://www.google.com/maps/search/?api=1&query={name.replace(" ","%20")}%2C%20Coorg%2C%20Karnataka" class="btn btn-ghost btn-sm" target="_blank" rel="noopener">ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ನೋಡಿ</a></div></article>' for p,alt,tag,name,d,mins in attrs])

for filename,(title,desc,body) in pages.items():
    body=body.replace('{ROOMCARDS}',roomcards).replace('{GALLERY}',gallery).replace('{ATTRACTIONS}',attractions)
    kn.joinpath(filename).write_text(shell(title,desc,filename,body),encoding='utf-8')

# language-specific styling: load web-safe Unicode Kannada fonts from Google as fallback; Sanchaya-listed Nudi/Inchara remain fallback names.
(root/'css'/'kannada.css').write_text('''/* Kannada typography layer. Sanchaya is the Kannada font catalogue; this stack uses Unicode-safe Kannada rendering with Sanchaya-listed font names as local fallbacks. */\n@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+Kannada:wght@400;500;600;700&family=Noto+Serif+Kannada:wght@500;600;700&display=swap");\n''',encoding='utf-8')
# Add CSS import to kn pages after style.css
for f in kn.glob('*.html'):
    s=f.read_text(encoding='utf-8').replace('<link rel="stylesheet" href="../css/style.css">','<link rel="stylesheet" href="../css/style.css"><link rel="stylesheet" href="../css/kannada.css">')
    f.write_text(s,encoding='utf-8')
print('created',len(list(kn.glob('*.html'))),'Kannada pages')
